const THEME_COLORS = {
  PRIMARY: '#4889FF',
  SECONDARY: '#3CBCD5',
  SUCCESS: '#5BC695',
  WARNING: '#FFA844',
  WARNING_STRONG: '#FF851C',
  DANGER: '#E55858',
  DANGER_LIGHT: '#F1AAAA',
  INFO: '#8C95A8',
  INFO_LIGHT: '#CDD4E2',
  VIOLET: '#BD7ADB',
  WHITE: '#FFFFFF',
  FONT_REGULAR: '#3F506A',
  FONT_BOLD: '#3A3A3A',
  FONT_NORMAL: '#8E8E93',
  FONT_LIGHT: '#D0CECE',
  LINES: '#EFEFEF',
  BACKGROUND_DARK: '#F4F7FC',
  DISABLED: '#bed5ff',
  TRANSFER_LITRES: '#785DD3'
};

export default THEME_COLORS;
